### ISSUE TITLE
MultipleDevices

### ISSUE THREAD

**Issue by yaman-taku** [mugifly/homeassistant-mornin#4]
Dear developer,

How can I set these for my multiple Devices?

Thanks in advance.

**Comment by mugifly** [comment]
Hi, @yaman-taku.

You can make a configuration for multiple devices as follows.
This syntax is the same as the other Home Assistant components.

```
cover:
  - platform: mornin
    api_key: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    mac: 'xx:xx:xx:xx:xx:xx'
    name: 'Curtain of Living'
    reverse: false
  - platform: mornin
    api_key: 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy'
    mac: 'yy:yy:yy:yy:yy:yy'
    name: 'Curtain of Dining'
    reverse: false
```

But I have only one device, so I can't guarantee that this component will work properly on multiple devices.
